# Generated by Django 4.1.4 on 2022-12-25 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='dreated_at',
            new_name='created_at',
        ),
    ]
